/**
 * 应用权限定义
 */

export const PERMISSIONS = {
  // 用户管理
  VIEW_USERS: 'view_users',
  CREATE_USER: 'create_user',
  EDIT_USER: 'edit_user',
  DELETE_USER: 'delete_user',

  // 问答管理
  CREATE_QUESTION: 'create_question',
  EDIT_QUESTION: 'edit_question',
  DELETE_QUESTION: 'delete_question',
  CREATE_ANSWER: 'create_answer',
  EDIT_ANSWER: 'edit_answer',
  DELETE_ANSWER: 'delete_answer',

  // 系统管理
  MANAGE_SYSTEM: 'manage_system',
  VIEW_ANALYTICS: 'view_analytics',
};

/**
 * 角色权限映射
 */
export const ROLE_PERMISSIONS = {
  admin: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.EDIT_USER,
    PERMISSIONS.DELETE_USER,
    PERMISSIONS.CREATE_QUESTION,
    PERMISSIONS.EDIT_QUESTION,
    PERMISSIONS.DELETE_QUESTION,
    PERMISSIONS.CREATE_ANSWER,
    PERMISSIONS.EDIT_ANSWER,
    PERMISSIONS.DELETE_ANSWER,
    PERMISSIONS.MANAGE_SYSTEM,
    PERMISSIONS.VIEW_ANALYTICS,
  ],
  user: [
    PERMISSIONS.CREATE_QUESTION,
    PERMISSIONS.EDIT_QUESTION,
    PERMISSIONS.DELETE_QUESTION,
    PERMISSIONS.CREATE_ANSWER,
    PERMISSIONS.EDIT_ANSWER,
    PERMISSIONS.DELETE_ANSWER,
  ],
  moderator: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.CREATE_QUESTION,
    PERMISSIONS.EDIT_QUESTION,
    PERMISSIONS.DELETE_QUESTION,
    PERMISSIONS.CREATE_ANSWER,
    PERMISSIONS.EDIT_ANSWER,
    PERMISSIONS.DELETE_ANSWER,
    PERMISSIONS.MANAGE_SYSTEM,
  ],
};